steps:
    # Set up git with key and domain
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['-']
    id: 'docker-build-gke'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gke:$REVISION_ID'
      - '.'

  # Dockerイメージをpush
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['docker-build-gke']
    id: 'docker-push-hash'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/gke:$REVISION_ID'

  # GKEにデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['docker-push-hash']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get -y install gettext
        kubectl apply -f <(envsubst <./k8s/deployment.yml | sed 's/gke:latest/gke:${REVISION_ID}/g')

timeout: 1800s
